In [1]:
import pandas as pd 
import scipy.stats as stats 
url = "https://raw.githubusercontent.com/dataprofessor/data/refs/heads/master/penguins_cleaned.csv"
df = pd.read_csv(url)
df.head(2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181,3750,male
1,Adelie,Torgersen,39.5,17.4,186,3800,female

In [2]:
df.corr(numeric_only = True)

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,1.000000,-0.228626,0.653096,0.589451
bill_depth_mm,-0.228626,1.000000,-0.577792,-0.472016
flipper_length_mm,0.653096,-0.577792,1.000000,0.872979
body_mass_g,0.589451,-0.472016,0.872979,1.000000

In [3]:
for col1 in df.columns:
    for col2 in df.columns: 
        iscol1num = pd.api.types.is_numeric_dtype(df[col1])
        iscol2num = pd.api.types.is_numeric_dtype(df[col2])
        if col1 ==col2: 
            continue 
        if not iscol1num or not iscol2num: 
            continue

In [4]:
r,p = stats.pearsonr(df['body_mass_g'], df['flipper_length_mm'])
print(r,p)
r2 = r**2
print(r2) #flipper length is 76% dependent on body mass

0.8729788985653616 3.1328362509712585e-105
0.7620921573403919

In [5]:
r,p = stats.pearsonr(df['body_mass_g'], df['bill_length_mm'])
r2 = r**2 #bill length is 34% dependent on body mass of the penguins 

print(r,p,r2)

0.5894511101769491 1.5386135144859492e-32 0.34745261128883775