In [82]:
import pandas as pd

url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/soccer-players.csv"

df = pd.read_csv(url)
df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [83]:
def convert_height(cm):
    """
    Convert cm to feet
    
    Args:
        cm (int): the Num of cm
    Returns:
        feet (float): num of feet.
    """
    return (cm * 0.393701) / 12

In [84]:
df["height_in_ft"] = df["height_in_cm"].apply(convert_height)
df["height_in_ft"]

0        6.036749
1        6.233599
2             NaN
3             NaN
4        6.364833
           ...
32398    5.839898
32399    5.905515
32400    5.380580
32401         NaN
32402         NaN
Name: height_in_ft, Length: 32403, dtype: float64

In [85]:
df.describe()

,player_id,last_season,current_club_id,height_in_cm,market_value_in_eur,highest_market_value_in_eur,height_in_ft
count,3.240300e+04,32403.000000,32403.000000,30059.000000,3.086900e+04,3.086900e+04,30059.000000
mean,3.445789e+05,2019.337777,4809.252045,182.291161,1.611350e+06,3.675045e+06,5.980684
std,2.806831e+05,3.965914,11601.982978,6.971224,6.362017e+06,9.653897e+06,0.228715
min,1.000000e+01,2012.000000,3.000000,17.000000,1.000000e+04,1.000000e+04,0.557743
25%,1.066980e+05,2016.000000,403.000000,178.000000,1.000000e+05,2.750000e+05,5.839898
50%,2.824210e+05,2020.000000,1071.000000,183.000000,2.500000e+05,8.000000e+05,6.003940
75%,5.242085e+05,2023.000000,3060.000000,187.000000,7.000000e+05,2.800000e+06,6.135174
max,1.309800e+06,2024.000000,110302.000000,207.000000,2.000000e+08,2.000000e+08,6.791342

In [86]:
df["height_in_cm"].std()

6.971224376399549

In [87]:
df["height_in_ft"].var()
df["height_in_ft"].std()

0.22871483401772097

In [88]:
df["height_in_ft"].mean()

np.float64(5.980684355462036)

In [89]:
# df["height_in_cm"] / df["height_in_ft"] 12

In [90]:
df["height_in_cm"].median()

183.0

In [91]:
df["height_in_cm"].mode(0)[0]

np.float64(nan)

In [92]:
df["height_in_cm"].quantile(.33)

np.float64(179.0)

In [93]:
df["height_in_cm"].min()

17.0

In [94]:
df["height_in_cm"].max()

207.0

In [95]:
range = df["height_in_cm"].max() - df["height_in_cm"].min()
range

190.0

In [96]:
df["height_in_cm"].skew()

np.float64(-1.7751475048518246)

In [97]:
from scipy import stats

sk = stats.skew(df["height_in_cm"], nan_policy = "omit")
sk

np.float64(-1.7750589204621978)

In [98]:
df["height_in_cm"].kurt()

np.float64(40.3723954752419)

In [99]:
stats.kurtosis(df["height_in_cm"].dropna())

np.float64(40.36548066183285)

In [100]:
def eda(df: pd.DataFrame) -> None:
    """
    Evaluate basic statistics on a DataFrame
    
    Args:
        df (Pandas.DataFrame): DataFrame to evaluate
    Returns:
        None
    """
    print(f"{'='*5}DF Shape: {df.shape}{'='*5}")
    num_cols = []
    cat_cols = []
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            num_cols.append(col) # -> "height_in_cm"
        else: 
            cat_cols.append(col)
   
    print(f"{'*'*3}NUMERIC COLUMNS{'*'*3}")
    for col in num_cols:
        n_min = df[col].min()
        n_max = df[col].max()
        num_na = df[col].isna().sum()
        print(col)
        print(f"\tNum NA: {num_na}")
        print(f"\t% NA: {(num_na / len(df)) * 100}%")
        print(f"\tMin: {n_min}")
        print(f"\tMax: {n_max}")
        print(f"\tRange: {n_max - n_min}")
        print(f"25%: {df[col].quantile(0.25)}")
        print(f"75%: {df[col].quantile(0.75)}")
        print(f"St. Dev.: {df[col].std()}")
        print(f"\tNum unique: {df[col].nunique()}")
    print("\n")
    print(f"{'*'*3} CATEGORICAL COLS{'*'*3}")
    for col in cat_cols:
        d = df[col]
        num_null = d.isna().sum()
        print(f"{col}")
        print(f"\tNum NA: {num_null}")
        print(f"\t% NA: {(num_null / len(df)) * 100}%")
        print(f"\tNum Uniques: {d.nunique()}")
        if d.nunique() < 7:
            print(f"Unique Vals: {d.unique()}")

In [101]:
eda(df)

=====DF Shape: (32403, 24)=====
***NUMERIC COLUMNS***
player_id
	Num NA: 0
	% NA: 0.0%
	Min: 10
	Max: 1309800
	Range: 1309790
25%: 106698.0
75%: 524208.5
St. Dev.: 280683.13989913743
	Num unique: 32403
last_season
	Num NA: 0
	% NA: 0.0%
	Min: 2012
	Max: 2024
	Range: 12
25%: 2016.0
75%: 2023.0
St. Dev.: 3.965914065614276
	Num unique: 13
current_club_id
	Num NA: 0
	% NA: 0.0%
	Min: 3
	Max: 110302
	Range: 110299
25%: 403.0
75%: 3060.0
St. Dev.: 11601.982977954987
	Num unique: 437
height_in_cm
	Num NA: 2344
	% NA: 7.233898095855322%
	Min: 17.0
	Max: 207.0
	Range: 190.0
25%: 178.0
75%: 187.0
St. Dev.: 6.971224376399549
	Num unique: 52
market_value_in_eur
	Num NA: 1534
	% NA: 4.734129555905318%
	Min: 10000.0
	Max: 200000000.0
	Range: 199990000.0
25%: 100000.0
75%: 700000.0
St. Dev.: 6362017.247132119
	Num unique: 129
highest_market_value_in_eur
	Num NA: 1534
	% NA: 4.734129555905318%
	Min: 10000.0
	Max: 200000000.0
	Range: 199990000.0
25%: 275000.0
75%: 2800000.0
St. Dev.: 9653897.3865907
	Num unique: 206
height_in_ft
	Num NA: 2344
	% NA: 7.233898095855322%
	Min: 0.5577430833333333
	Max: 6.7913422500000005
	Range: 6.233599166666667
25%: 5.839898166666667
75%: 6.135173916666667
St. Dev.: 0.22871483401772097
	Num unique: 52


*** CATEGORICAL COLS***
first_name
	Num NA: 2058
	% NA: 6.351263771872976%
	Num Uniques: 6966
last_name
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 23701
name
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 31708
player_code
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 31667
country_of_birth
	Num NA: 2803
	% NA: 8.650433601826991%
	Num Uniques: 185
city_of_birth
	Num NA: 2461
	% NA: 7.5949757738481%
	Num Uniques: 8537
country_of_citizenship
	Num NA: 380
	% NA: 1.1727309199765454%
	Num Uniques: 183
date_of_birth
	Num NA: 47
	% NA: 0.14504829799709903%
	Num Uniques: 9272
sub_position
	Num NA: 185
	% NA: 0.5709347899885814%
	Num Uniques: 13
position
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 5
Unique Vals: ['Attack' 'Goalkeeper' 'Defender' 'Midfield' 'Missing']
foot
	Num NA: 2593
	% NA: 8.002345461839953%
	Num Uniques: 3
Unique Vals: ['right' 'left' nan 'both']
contract_expiration_date
	Num NA: 12131
	% NA: 37.43789155325124%
	Num Uniques: 114
agent_name
	Num NA: 16015
	% NA: 49.424436009011515%
	Num Uniques: 2833
image_url
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 26561
url
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 32403
current_club_domestic_competition_id
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 14
current_club_name
	Num NA: 0
	% NA: 0.0%
	Num Uniques: 437